### ISSUE TITLE
Declare plugin in Gradle's plugin portal.

### ISSUE THREAD

**Issue by glaforge** [GoogleCloudPlatform/app-gradle-plugin#371] opened 2019-11-29 15:29 UTC
Currently, to use the Gradle App Engine plugin, developers have to add the following to their build script:

```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.cloud.tools:appengine-gradle-plugin:2.2.0'
    }
}

apply plugin: "com.google.cloud.tools.appengine-appyaml"
```

But if we declare the plugin to the [Gradle plugin portal](https://plugins.gradle.org/), it's possible to simplify the steps above, by replacing them with a new entry in the plugins block:

```
plugins {
  id “com.google.cloud.tools.appengine-appyaml” version “2.2.0"
}
```

To submit and declare the plugin in the portal, you can follow the instructions [here](https://plugins.gradle.org/docs/submit).

**Comment by loosebazooka** [comment] 2020-09-21 15:01
So `2.4.1`  (unreleased) should have a fix for this where you can use the plugins block (with some extra config in settings.gradle to pull from mavenCentral).

**Comment by loosebazooka** [comment] 2020-09-21 16:43
marking duplicate of #300

**Closed by loosebazooka** 2020-09-21 16:43 UTC
